# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "super-cart"
client_id = "0523518337bdfb0a2340016b919e85d0"
application_url = "https://necessary-advertisers-highlight-holmes.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes, write_themes, read_content, write_content, read_products"

[auth]
redirect_urls = [
  "https://necessary-advertisers-highlight-holmes.trycloudflare.com/auth/callback",
  "https://necessary-advertisers-highlight-holmes.trycloudflare.com/auth/shopify/callback",
  "https://necessary-advertisers-highlight-holmes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demowil.myshopify.com"
